import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App2",
    description: "Generated by create next app",
  };

export default function DashboardLayout({children,}: {children: React.ReactNode}) {
    return <section>{children}</section>
  }